#   run: touch release/wwwroot/.nojekyll

- name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@v4.7.2
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    BRANCH: gh-pages
    FOLDER: release/wwwroot